name: Build
on:
  workflow_call:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

env:
  PACKAGE_VERSION: ${{ fromJson(github.event.head_commit.message).version || github.ref_name }}

permissions: write-all

jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
          - ia32
          - arm64
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Generate Changelog
        if: startsWith(github.ref, 'refs/tags/v')
        run: npm run changelog
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate checksums
        run: |
          Get-FileHash dist/*setup.exe -Algorithm SHA256 | ForEach-Object {
            $_.Hash > "$($_.Path).sha256"
          }
      - name: Upload Artifacts
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: Windows ${{ matrix.arch }}
          path: |
            dist/*.sha256
            dist/*setup.exe
          if-no-files-found: error
      - name: Publish Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.sha256
            dist/*setup.exe
          body_path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  linux:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
          - arm64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Generate Changelog
        if: startsWith(github.ref, 'refs/tags/v')
        run: npm run changelog
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build:linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate checksums
        run: |
          for file in dist/*.{deb,AppImage}; do
            sha256sum "$file" > "$file.sha256"
          done
      - name: Upload Artifacts
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: Linux ${{ matrix.arch }}
          path: |
            dist/*.sha256
            dist/*.deb
            dist/*.AppImage
          if-no-files-found: error
      - name: Publish Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.sha256
            dist/*.deb
            dist/*.AppImage
          body_path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  macos:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
          - arm64
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Generate Changelog
        if: startsWith(github.ref, 'refs/tags/v')
        run: npm run changelog
      - name: Install Dependencies
        run: npm install
      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build:mac
      - name: Generate checksums
        run: |
          for file in dist/*.dmg; do
            shasum -a 256 "$file" > "$file.sha256"
          done

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.sha256
            dist/*setup.exe
            dist/*.deb
            dist/*.AppImage
            dist/*.dmg
          body_path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}